# Config file for LightningAE_UNET_5pct_256_v1_TIODataModule_bz2_176x16x200_k0_e400
project_name: LowdosePET-PiBVision
version_name: UNET_5pct_256_v1
precision: 32
epoch: 400
batch_size: 2
acc_grad_batches: 1
module: LightningAE
generator: FAN3D_fix
depth_S: 1
g_optimizer: Adam
g_lr: 1e-4
g_weight_decay: 0
lr_scheduler: exponential_decay_0.01
g_loss: MeanAbsoluteError
data_split_pkl: PiBVision_train_test_split_6_fold.json
data_generator: TIODataModule
data_folder: /homes/raphael/Projects/LowdosePET2/PiBVision/data_for_training
patient_info_csv: PiBVision_anonymized_patient_info.csv
pet_normalization_constant: 32676
augment: true
data_shape: [256, 256, 256]
patch_size: [176, 16, 200]     # when using Crop preprocess step
repeat_patient_list: 1
input_files:
  name: [PET_2mm_LD5pct_MNI_BET_176x176x200_NORM.nii.gz]
  preprocess_step: [null]
target_files:
  name: [PET_5mm_MNI_BET_176x176x200_NORM.nii.gz]
  preprocess_step: [null]
cropping:
  x_lim: [43, 37]
  y_lim: [33, 47]
  z_lim: [16, 40]
plotting_callback:
  class: Image2ImageLogger
  num_plots: 16
  cmap: nipy_spectral
  viewing_axis: 1
  vmin:
  vmax:
early_stopping_callback:
  monitor: val_loss
  patience: 50
freeze_encoder: false
build_date: 20211212-165135
color_channels_in: 1
data_shape_in:
- 1
- 176
- 16
- 200
project_dir: /homes/raphael/Projects/LowdosePET2/PiBVision
config_file: /homes/raphael/Projects/LowdosePET2/PiBVision/config.yaml
k_fold: 0
hostname: ross
GPUs: 4
global_batch_size: 8
rhtorch_version: 0.1.3
pytorch_version: 1.10.0
torchio_version: 0.18.70
pytorch_lightning_version: 1.5.4
model_name: LightningAE_UNET_5pct_256_v1_TIODataModule_bz2_176x16x200_k0_e400
best_model: /homes/raphael/test_app/Checkpoint_best_model_PiB_5pct.ckpt
